### ISSUE TITLE
The copy button is displayed weirdly 

### ISSUE THREAD

**Issue by mthuret** [Kilix/storybook-addon-jsx#1] opened 2017-04-25 14:11 UTC
Hi,

I tried to add your nice addon, but the copy button is messing with other addons, see:
![image](https://cloud.githubusercontent.com/assets/6885378/25389735/b4e3629e-29d1-11e7-8047-bd029abb55d2.png)

Maybe it would be better to put it like the action logger does, at the bottom right?

**Comment by wcastand** [comment] 2017-04-25 14:57
Hi,

Thanks for the feedback :)

You're right i totally forgot about other plugins, sorry about that.

I took your advice and put the button at the bottom right like other plugins.
I publish the new version on npm.

I'm waiting for your confirmation before closing this issue :)

**Comment by mthuret** [comment] 2017-04-25 15:29
Indeed, bottom right might not be the best idea :( 

If you're using panels on the right, then because of the size of the jsx text, then you need to scroll right. 

Putting it at the top left make maybe more sense for this action. What do you think?

I'm sorry about that.

**Comment by wcastand** [comment] 2017-04-25 15:47
I think i have an idea and can put the button in the title of the panel (it accept Component apparently).

I'll do that in the evening :)

**Comment by wcastand** [comment] 2017-04-25 21:20
So i put the button in the title of the panel and it works fine. Only problem is, storybook doesn't center his title, so mine is center but other title are not aligned.

I'll make a issue on storybook and see if there is a possibility to center the title of panels.

**Comment by wcastand** [comment] 2017-04-28 15:02
The PR in storybook as been merged. I don't know when it's going to be publish but it should be good and all titles will be centered now :)

Let me now if you have any problems or questions :)

Can we close this issue ? :)

**Comment by wcastand** [comment] 2017-05-09 13:03
I guess the issue is fixed.
If you have any problem, let us know.

And thanks again for the feedback :)

**Closed by wcastand** 2017-05-09 13:03 UTC
